# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_and_test:
    machine:
       image: ubuntu-1604:201903-01

    #docker:
    #  - image: circleci/openjdk:16-ea-11-jdk-buster

    # Need to disable RYUK with Java testcontainers --
    # RYUK requires privileged containers.
    #environment:
    #  TESTCONTAINERS_RYUK_DISABLED: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set credentials
          command: |
            echo $GCLOUD_SERVICE_KEY > $HOME/gcloud-service-key.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json' >> $BASH_ENV

      #- setup_remote_docker

      - run:
          name: get docker version
          command: |
            docker version
            docker run hello-world

      - run:
          name: Build and run tests
          command: |
            ./gradlew build

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/reports

workflows:
  version: 2

  commit:  # Run on every commit.
    jobs:
      - build_and_test

  nightly:  # Run every night.
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                  - master
    jobs:
      - build_and_test
