# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_and_test:

    # Machine is required due to using Java testcontainers
    machine:
       image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build and run tests
          command: |
            ./gradlew --no-daemon build test shadowJar

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/libs

workflows:
  version: 2

  commit:  # Run on every commit.
    jobs:
      - build_and_test

  nightly:  # Run every night.
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                  - master
    jobs:
      - build_and_test
